Feature responsive navbar
se3-3124/spotless-solutions pull request #6
Opened 2024-02-22 13:22 UTC by Dave00913

2024-02-22 13:30 UTC, ohana-matsumae approved these changes
very cool

2024-02-22 13:31 UTC, candace1818 approved these changes
amazing

2024-02-25 05:45 UTC, ohana-matsumae requested changes

2024-02-25 05:45 UTC, ohana-matsumae commented on SpotlessSolutions.Web/ClientApp/src/components/navigation/Navbar.tsx
> +              src="src/assets/td_logo.jpg"
Use imports

2024-03-02 13:39 UTC, ohana-matsumae approved these changes

2024-03-02 13:48 UTC, closed without merging

2024-03-02 13:48 UTC, ohana-matsumae commented
Use the latest branch first and then make your changes there with related changes. This PR will be closed.